//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationDetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetali
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string CustomerAddress { get; set; }
        public string City { get; set; }
        public string images { get; set; }
    }
}
