//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationDetails.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InformationDetailsEntities : DbContext
    {
        public InformationDetailsEntities()
            : base("name=InformationDetailsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<CustomerDetali> CustomerDetalis { get; set; }

        public System.Data.Entity.DbSet<InformationDetails.Models.UserList> UserLists { get; set; }
    }
}
